version: '3.8'

services:
  load-balancer:
    build: .
    container_name: load-balancer
    ports:
      - "8080:8080"  # Maps container port to host port
    # Use extra_hosts to access macOS host services from container
    # host-gateway is a special value that Podman resolves to the host's gateway IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Basic Configuration
      LISTENER_PORT: "8080"
      CONNECTION_TIMEOUT: "5000"  # Timeout in milliseconds
      LOAD_BALANCING_ALGORITHM: "ROUND_ROBIN"  # Options: ROUND_ROBIN, WEIGHTED, STICKY, LRT
      
      # Target Group 1: Backend servers
      # Use host.docker.internal to reach services on macOS host (resolves via extra_hosts above)
      TARGET_GROUP_1_NAME: "backend"
      TARGET_GROUP_1_TARGETS: "host.docker.internal:8081,host.docker.internal:8082,host.docker.internal:8083"
      
      # Listener Rule 1: Root path routing
      LISTENER_RULE_1_PATH_PREFIX: "/"
      LISTENER_RULE_1_PATH_REWRITE: ""
      LISTENER_RULE_1_TARGET_GROUP: "backend"

      HEADER_CONVENTION_ENABLE: "true"
      
      # Example: Additional target groups and listener rules can be added like this:
      # TARGET_GROUP_2_NAME: "api_backend"
      # TARGET_GROUP_2_TARGETS: "api1.example.com:8080,api2.example.com:8080"
      # LISTENER_RULE_2_PATH_PREFIX: "/api"
      # LISTENER_RULE_2_PATH_REWRITE: "/api"
      # LISTENER_RULE_2_TARGET_GROUP: "api_backend"

